apiVersion: "apps/v1beta2"
kind: "Deployment"
metadata:
  name: "httpd"
spec:
  replicas: 2
  selector:
    matchLabels:
      name: "httpd"
  template:
    metadata:
      labels:
        name: "httpd"

    spec:
      containers:
        - name: "httpd"
          image: "httpd:latest"
          imagePullPolicy: "IfNotPresent"

          readinessProbe:
            httpGet:
              port: 80
              path: "/index.html"
            initialDelaySeconds: 5
            periodSeconds: 5

          ports:
            - containerPort: 80
