apiVersion: "v1"
kind: "Service"
metadata:
  name: "httpd"
spec:
  type: NodePort

  ports:
    - name: ui
      port: 80
      targetPort: 80
      nodePort: 30081
  selector:
    name: "httpd"
---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "httpd"
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxUnavailable: '50%'
  template:
    metadata:
      name: "httpd"
      labels:
        name: "httpd"

    spec:
      containers:
        - name: "httpd"
          image: "httpd:latest"
          imagePullPolicy: "Never"

          ports:
            - containerPort: 80
