apiVersion: "apps/v1beta2"
kind: "Deployment"
metadata:
  name: "jenkins"
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  selector:
    matchLabels:
      name: "jenkins"
  template:
    metadata:
      labels:
        name: "jenkins"

    spec:
      containers:
        - name: "jenkins"
          image: "jenkins:0.0.1"
          imagePullPolicy: "Never"

          readinessProbe:
            httpGet:
              path: /login
              port: 8080
            initialDelaySeconds: 10

          ports:
            - containerPort: 80
            - containerPort: 30050

          volumeMounts:
            - name: "jenkins-jobs"
              mountPath: "/var/jenkins/jobs"

      volumes:
        - name: "jenkins-jobs"
          persistentVolumeClaim:
            claimName: "jenkins-jobs"
