apiVersion: "v1"
kind: "Service"
metadata:
  name: "jenkins"
spec:
  type: NodePort

  ports:
    - name: ui
      port: 80
      targetPort: 8080
      nodePort: 30081
    - name: slave
      port: 50000
      targetPort: 50000
  selector:
    name: "jenkins"
---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "jenkins"
spec:
  replicas: 1
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
  template:
    metadata:
      name: "jenkins"
      labels:
        name: "jenkins"

    spec:
      containers:
        - name: "jenkins"
          image: "jenkins:latest"
          imagePullPolicy: "Never"

          ports:
            - containerPort: 8080
            - containerPort: 50000

          volumeMounts:
            - name: "jenkins-jobs"
              mountPath: "/var/jenkins_home/jobs"
            - name: "jenkins-nodes"
              mountPath: "/var/jenkins_home/nodes"


      volumes:
        - name: jenkins-jobs
          persistentVolumeClaim:
            claimName: "jenkins-jobs"
        - name: jenkins-nodes
          persistentVolumeClaim:
            claimName: "jenkins-nodes"
