apiVersion: "apps/v1beta2"
kind: "Deployment"
metadata:
  name: "jenkins"
spec:
  strategy:
    type: "Recreate"
  selector:
    matchLabels:
      name: "jenkins"
  template:
    metadata:
      labels:
        name: "jenkins"

    spec:
      serviceAccountName: "jenkins"

      containers:
      - name: "jenkins"
        image: "jenkins:0.0.1"
        imagePullPolicy: "Never"

        readinessProbe:
          httpGet:
            path: /login
            port: 80
          initialDelaySeconds: 30

        ports:
        - containerPort: 80
        - containerPort: 30050

        volumeMounts:
        - name: "jenkins-data"
          subPath: "jobs"
          mountPath: "/var/jenkins/jobs"
        - name: "jenkins-data"
          subPath: "nodes"
          mountPath: "/var/jenkins/nodes"
        - name: "jenkins-data"
          subPath: "users"
          mountPath: "/var/jenkins/users"
        - name: "jenkins-config"
          mountPath: "/etc/config"
          readOnly: true

      volumes:
      - name: "jenkins-data"
        persistentVolumeClaim:
          claimName: "jenkins-data"
      - name: "jenkins-config"
        configMap:
          name: "jenkins"
