apiVersion: "v1"
kind: "Service"
metadata:
  name: "jenkins"
spec:
  type: NodePort

  ports:
    - name: ui
      port: 80
      targetPort: 80
      nodePort: 30080
    - name: slave
      port: 30050
      targetPort: 30050
      nodePort: 30050
  selector:
    name: "jenkins"
---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "jenkins"
spec:
  replicas: 1
  minReadySeconds: 5
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      name: "jenkins"
      labels:
        name: "jenkins"

    spec:
      containers:
        - name: "jenkins"
          image: "jenkins:latest"
          imagePullPolicy: "Never"

          readinessProbe:
            httpGet:
              port: 8080
              path: /robots.txt
            initialDelaySeconds: 10
            periodSeconds: 5

          ports:
            - containerPort: 80
            - containerPort: 30050

          volumeMounts:
            - name: "jenkins-jobs"
              mountPath: "/var/jenkins_home/jobs"

      volumes:
        - name: jenkins-jobs
          persistentVolumeClaim:
            claimName: "jenkins-jobs"
