apiVersion: "apps/v1beta2"
kind: "Deployment"
metadata:
  name: "tiller"
  namespace: "kube-system"
spec:
  selector:
    matchLabels:
      name: "tiller"
  template:
    metadata:
      labels:
        name: "tiller"

    spec:
      containers:
      - name: "tiller"
        image: "gcr.io/kubernetes-helm/tiller:v2.7.2"
        imagePullPolicy: "IfNotPresent"

        env:
        - name: "TILLER_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: "TILLER_HISTORY_MAX"
          value: "0"

        readinessProbe:
          httpGet:
            path: "/readiness"
            port: 44135
          initialDelaySeconds: 1
          timeoutSeconds: 1

        livenessProbe:
          httpGet:
            path: "/liveness"
            port: 44135
          initialDelaySeconds: 1
          timeoutSeconds: 1

        ports:
        - containerPort: 44134
