apiVersion: "apps/v1beta2"
kind: "Deployment"
metadata:
  name: "vault"
spec:
  replicas: 1
  selector:
    matchLabels:
      name: "vault"
  template:
    metadata:
      labels:
        name: "vault"

    spec:
      containers:
        - name: "vault"
          image: "vault:latest"
          imagePullPolicy: "IfNotPresent"

          args: ["server"]

          env:
            - name: "SKIP_SETCAP"
              value: "true"
            - name: "VAULT_LOCAL_CONFIG"
              value: '{
                "default_lease_ttl": "168h",
                "max_lease_ttl": "720h",
                "backend": {
                  "file": {
                    "path": "/vault/file"
                  }
                },
                "listener": {
                  "tcp": {
                    "address": "0.0.0.0:8200",
                    "tls_disable": 1
                  }
                },
                "disable_mlock": true
              }'

          ports:
            - containerPort: 8200

          volumeMounts:
            - name: "vault-data"
              mountPath: "/vault/file"

      volumes:
        - name: "vault-data"
          persistentVolumeClaim:
            claimName: "vault-data"
