apiVersion: "rbac.authorization.k8s.io/v1beta1"
kind: "Role"
metadata:
  name: "jenkins"
  namespace: "default"
rules:
- apiGroups: ["*"]
  resources:
    - pods
  verbs: ["create","list","watch","get","delete"]
