apiVersion: "v1"
kind: "Service"
metadata:
  name: "jenkins"
spec:
  type: "NodePort"

  ports:
  - name: "ui"
    port: 80
    nodePort: 30080
  - name: "slave"
    port: 30050
    nodePort: 30050

  selector:
    name: "jenkins"
