def image;
def commit;

echo "Spawning a slave for this job..."

node("docker") {
    stage("Clone") {
        git branch: 'development', url: "https://github.com/Artiax/kubernetes.git", changelog: false, poll: false
        commit = sh(returnStdout: true, script: "git rev-parse HEAD").trim().take(8)
    }

    stage("Build") {
        dir('images/httpd') {
            sh 'sed -ri "s/COMMIT_ID/${commit}/" index.html'
            image = docker.build 'httpd'
        }
    }

    stage("Tag") {
        image.tag "${commit}"
        image.tag "latest"
    }
}

timeout(time: 15, unit: 'MINUTES') {
    try {
        input(id: 'deploy', message: 'Deploy this image?')
        build job: 'deployments/httpd', parameters: [string(name: 'TAG', value: "${commit}")], wait: false
    } catch(err) {
        currentBuild.result = 'SUCCESS'
    }
}
